version: '3.3'

services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    networks:
      - docker-media-server_default
    environment:
      TZ: "America/Argentina/Buenos_Aires"
    volumes:
      - ${STORAGE_LOCATION}/jdownloader/downloads:/output:rw
      - ${STORAGE_LOCATION}/jdownloader/config:/config:rw
    labels:
      - "traefik.enable=true"
      - "traefik.port=5800"
      - "traefik.backend=jdownloader"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:downloads.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=https://auth.${DOMAIN_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true

networks:
  docker-media-server_default:
    external: true
