version: '3.3'

services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    networks:
      - docker-media-server_default
    environment:
      TZ: "America/Argentina/Buenos_Aires"
    volumes:
      - ${STORAGE_LOCATION}/jdownloader/downloads:/output:rw
      - ${STORAGE_LOCATION}/jdownloader/config:/config:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.jdownloader.rule=Host(`jdownloader.${DOMAIN_URL}`)"
      - "traefik.http.routers.jdownloader.tls=true"
      - "traefik.http.routers.jdownloader.entrypoints=websecure,web"
      - "traefik.http.routers.jdownloader.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.jdownloader.loadbalancer.server.port=80"

networks:
  main:
    external: true
