version: '3.3'

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2-debian
    restart: unless-stopped
    entrypoint: /bin/sh -c "if [ ! -f /data/database.db ]; then /filebrowser config import /.filebrowser.json;/filebrowser users import /users.json; fi;/filebrowser"
    volumes:
      - ${FILEBROWSER_HOME}:/srv
      - ${STORAGE_LOCATION}/filebrowser/data:/data
      - ${STORAGE_LOCATION}/filebrowser/filebrowser.json:/.filebrowser.json
      - ${STORAGE_LOCATION}/filebrowser/users.json:/users.json
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=main"
      - "traefik.http.routers.filebrowser.rule=Host(`cloud.${DOMAIN_URL}`)"
      - "traefik.http.routers.filebrowser.tls=true"
      - "traefik.http.routers.filebrowser.entrypoints=websecure,web"
      - "traefik.http.routers.filebrowser.middlewares=traefik-forward-auth,tls-headers"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
    networks:
      - main

networks:
  main:
    external: true
