version: '3.3'

services:
  disk-scanner:
    image: dantebarba/diskspacescanner:latest
    container_name: disk-scanner
    volumes:
      - ${STORAGE_LOCATION}/radarr/movies:/movies
      - ${STORAGE_LOCATION}/sonarr/tvseries:/tv
    environment:
      SCAN_DIRS: ${SCAN_DIRS}
      FREE: ${FREE}
      THRESHOLD: ${THRESHOLD}
      LOG_LEVEL: ${LOG_LEVEL}