version: '3.6'

services:
  disk-scanner:
    image: dantebarba/diskspacescanner:4.0.3
    container_name: disk-scanner
    volumes:
      - ${STORAGE_LOCATION}/radarr/movies:/movies
      - ${STORAGE_LOCATION}/sonarr/tvseries:/tv
    environment:
      SCAN_DIRS: ${SCAN_DIRS}
      FREE: ${FREE}
      THRESHOLD: ${THRESHOLD}
      LOG_LEVEL: ${LOG_LEVEL}
      DRY_RUN: ${DRY_RUN}
      AUTH_USER: ${AUTH_USER}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      SOURCE_REMOTE: ${SOURCE_REMOTE}
      DESTINATION_REMOTE: ${DESTINATION_REMOTE}
      RCLONE_URL: ${RCLONE_URL}
      TZ: ${DOCKER_TZ}
      REMOTE_PATH_MAPPING: ${REMOTE_PATH_MAPPING}
      SCHEDULED: ${SCHEDULED}
      HEALTHCHECK: ${HEALTHCHECK}