version: '3.3'

services:
  disk-scanner:
    image: dantebarba/diskspacescanner:latest
    container_name: disk-scanner
    command: echo test
    volumes:
      - ${STORAGE_LOCATION}/radarr/movies:/movies
      - ${STORAGE_LOCATION}/sonarr/tvseries:/tv
    environment:
      SCAN_DIRS: ${SCAN_DIRS}
      FREE: ${FREE}
      THRESHOLD: ${THRESHOLD}
      LOG_LEVEL: ${LOG_LEVEL}
      DRY_RUN: ${DRY_RUN}
      AUTH_USER: ${AUTH_USER}
      AUTH_PASSWORD: ${AUTH_PASSWORD}
      SOURCE_REMOTE: ${SOURCE_REMOTE}
      DESTINATION_REMOTE: ${DESTINATION_REMOTE}
      RCLONE_URL: ${RCLONE_URL}
      REMOTE_PATH_MAPPING: "test"