  version: '3.7'

  services:
    gdrive-move-torrents:
      image: pfidr/rclone:latest
      container_name: gdrive-move-torrents
      restart: unless-stopped
      volumes:
        - ${STORAGE_LOCATION}/qbittorrent/downloads/complete:/source
        - ${STORAGE_LOCATION}/gdrive:/config
      environment:
        SYNC_SRC: /source
        SYNC_DEST: ${GDRIVE_SERVICE}:/torrent/complete
        SYNC_OPTS: '--log-level ${LOG_LEVEL} --delete-empty-src-dirs --stats 120s --buffer-size 128M --drive-chunk-size 128M --use-mmap --timeout 1m'
        RCLONE_DIR_CHECK_SKIP: 'true'
        RCLONE_CMD: move
        TZ: ${DOCKER_TZ}
        CRON: ${MOVE_CRON}
        UID: ${PUID}
        GID: ${PGID}