  version: '3.7'

  services:
    gdrive-move-torrents:
      image: pfidr/rclone:latest
      container_name: gdrive-move-torrents
      restart: unless-stopped
      volumes:
        - ${STORAGE_LOCATION}/qbittorrent/downloads/complete:/source
        - ${STORAGE_LOCATION}/gdrive:/config
      environment:
        SYNC_SRC: /source
        SYNC_DEST: ${GDRIVE_SERVICE}:/torrent/complete
        SYNC_OPTS: '--log-level ${LOG_LEVEL} --delete-empty-src-dirs --stats 120s --buffer-size 128M --drive-chunk-size 128M --use-mmap --timeout 1m --exclude *sample*'
        RCLONE_DIR_CHECK_SKIP: 'true'
        RCLONE_CMD: move
        TZ: ${DOCKER_TZ}
        CRON: ${MOVE_CRON}
        UID: ${PUID}
        GID: ${PGID}

    gdrive-move-nzb:
      image: pfidr/rclone:latest
      container_name: gdrive-move-nzb
      restart: unless-stopped
      volumes:
        - ${STORAGE_LOCATION}/nzbget/downloads/completed:/source
        - ${STORAGE_LOCATION}/gdrive:/config
      environment:
        SYNC_SRC: /source
        SYNC_DEST: ${GDRIVE_SERVICE}:/nzb/complete
        SYNC_OPTS: '--log-level ${LOG_LEVEL} --delete-empty-src-dirs --stats 120s --buffer-size 128M --drive-chunk-size 128M --use-mmap --timeout 1m --exclude _unpack/'
        RCLONE_DIR_CHECK_SKIP: 'true'
        RCLONE_CMD: move
        TZ: ${DOCKER_TZ}
        CRON: ${MOVE_CRON}
        UID: ${PUID}
        GID: ${PGID}

    rclone-sa-autoswap:
      image: dantebarba/rclone-sa-autoswap:latest
      container_name: rclone-sa-autoswap
      restart: unless-stopped
      volumes:
        - ${STORAGE_LOCATION}/gdrive:/config
      environment:
        CRON: ${AUTOSWAP_CRON} # will renew the SA number once every hour
        MAX_NUMBER: ${SA_NUMBER} # the number of SAs you generated
        PREFIX: ${SA_PREFIX} # the prefix with path included before the SA Number.
        PUID: ${PUID}
        PGID: ${PGID}
        TZ: ${DOCKER_TZ}
        # SAs should be named with the following schema: my-sa-{number}.json where number is the SA designated number.
        # this number should be sequential, from 1 to n.