version: '3.3'

services:
  nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    privileged: true
    ports:
      - "2049:2049"
    cap_add:
      - SYS_ADMIN      
    volumes:
      - ./export:/etc/exports:ro
      - ${STORAGE_LOCATION}/radarr/movies/local:/nfsroot/movies
    restart: unless-stopped