version: '3.3'

services:
  smb-server:
    image: dperson/samba
    container_name: smb-server
    privileged: true
    command: -p -u "example1;badpass" -s "public;/share"
    ports:
      - "139:139"
      - "445:445"     
    volumes:
      - ${STORAGE_LOCATION}/radarr/movies/local:/share/movies
    restart: unless-stopped