version: '3.3'

services:
  nfs-server:
    image: erichough/nfs-server
    container_name: nfs-server
    privileged: true
    ports:
      - "2049:2049"
    cap_add:
      - SYS_ADMIN
    environment:
      - NFS_EXPORT_0='/nfs-share                  *(rw,no_subtree_check)'
    volumes:
      - ${STORAGE_LOCATION}/transmission/downloads/complete:/nfs-share
    #   - ${STORAGE_LOCATION}/radarr/movies/local:/nfs-share/movies
    restart: unless-stopped