version: '3.3'

services:
  smb-server:
    image: dperson/samba
    container_name: smb-server
    privileged: true
    ports:
      - "139:139"
      - "445:445"     
    volumes:
      - ${STORAGE_LOCATION}/radarr/movies/local:/mount/movies
    restart: unless-stopped