version: '3.3'  
  
services:
  load-balancer:
    image: traefik:v1.7
    container_name: load-balancer
    restart: unless-stopped
    command:
      - "--acme"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.dnsChallenge.provider=cloudflare"
      - "--acme.dnsChallenge.delaybeforecheck=300"
      - "--acme.domains=${DOMAIN_URL}"
      - "--acme.domains=${WORDPRESS_URL}"
      - "--acme.onHostRule=true"
      - "--acme.acmelogging=true"
      - "--acme.email=${ACME_EMAIL}"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.watch=true"
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STORAGE_LOCATION}/traefik:/etc/traefik
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.docker.network=main"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=${OAUTH_FORWARD_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true

networks:
  main:
    external: true