version: '3.7'

services:
  plexdrive:
    image: rclone/rclone:beta
    container_name: plexdrive
    restart: unless-stopped
    command: "mount gdrive: /mnt/gdrive --config=/config/rclone/rclone_mount.conf --allow-other --gid ${PGID} --uid ${PUID} --buffer-size 256M --log-level ${LOG_LEVEL} --stats 2m --use-mmap --dir-cache-time 72h --poll-interval 30s"
    volumes:
      - ${STORAGE_LOCATION}/gdrive:/config/rclone
      - /mnt/gdrive:/mnt/gdrive:shared
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${DOCKER_TZ}
    labels:
      - "group=storage"

  watchdrive:
    image: rclone/rclone:beta
    container_name: watchdrive
    restart: unless-stopped
    command: "mount gdrive:/downloads/watch /mnt/gdrive --config=/config/rclone/rclone_mount.conf --allow-other --gid ${PGID} --uid ${PUID} --buffer-size 0M --log-level ${LOG_LEVEL} --stats 10m --use-mmap --poll-interval 10s --dir-cache-time 72h --checkers=1 --transfers=1"
    volumes:
      - ${STORAGE_LOCATION}/gdrive:/config/rclone
      - /mnt/watch:/mnt/gdrive:shared
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${DOCKER_TZ}
    labels:
      - "group=storage"