version: '3.7'

services:
  plexdrive:
    image: rclone/rclone:beta
    container_name: plexdrive
    restart: unless-stopped
    command: "mount gdrive: /mnt/gdrive --config=/config/rclone/rclone.conf --allow-other --gid ${PGID} --uid ${PUID} --buffer-size 256M --log-level ${LOG_LEVEL} --stats 2m --use-mmap --timeout 5m"
    volumes:
      - ${STORAGE_LOCATION}/gdrive:/config/rclone
      - /mnt/gdrive:/mnt/gdrive:shared
    privileged: true
    devices:
      - /dev/fuse
    cap_add:
      - MKNOD
      - SYS_ADMIN
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${DOCKER_TZ}