version: '2'

services:
  acestream:
    image: blaiseio/acestream
    container_name: acestream
    labels:
      - "traefik.enable=true"
      - "traefik.port=6878"
      - "traefik.backend=acestream"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:tv.${DOMAIN_URL}"
    networks:
      - docker-media-server_default

networks:
  docker-media-server_default:
    external: true
  default:
    driver: bridge