version: '3.3'
services:
    looking-glass:
        image: 'gmazoyer/looking-glass:latest'
        container_name: looking-glass
        labels:
            - "traefik.enable=true"
            - "traefik.port=80"
            - "traefik.backend=lookingglass"
            - "traefik.frontend.entryPoints=http,https"
            - "traefik.frontend.rule=Host:lg.${DOMAIN_URL}"
        networks:
            - docker-media-server_default

networks:
  docker-media-server_default:
    external: true