version: '3.3'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      TZ: "America/Argentina/Buenos_Aires"
    networks:
      - main
      - emontalti_net
    volumes:
      - ${STORAGE_LOCATION}/emontalti/www/html:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=wordpress"
      - "traefik.docker.network=emontalti_net"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:emontalti.${DOMAIN_URL}"

  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: db
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 1A2B3C4E
      MYSQL_ROOT_HOST: '%'
      TZ: "America/Argentina/Buenos_Aires"
    networks:
      - emontalti_net
    volumes:
      - emontalti_db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      TZ: "America/Argentina/Buenos_Aires"
    restart: unless-stopped
    networks:
      - emontalti_net
      - main
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=phpmyadmin"
      - "traefik.docker.network=main"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:phpmyadmin.${DOMAIN_URL}"
      - traefik.frontend.auth.forward.address=https://auth.${DOMAIN_URL}
      - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
      - traefik.frontend.auth.forward.trustForwardHeader=true

networks:
  emontalti_net:
    external: true
  main:
    external: true

volumes:
  emontalti_db: