version: '3.3'

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    privileged: true
    ports:
      - 1194:1194/udp
    volumes:
      - ${STORAGE_LOCATION}/openvpn:/etc/openvpn
    
