version: "2"

services:
  irc:
    image: linuxserver/thelounge
    container_name: irc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 9000:9000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.backend=irc"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:irc.${DOMAIN_URL}"