version: '2'

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: media.***REMOVED*** # set to fqdn of host
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    environment: 
      PGID: '999'
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro