version: '3.7'

services:

  gdrive-delete-torrents:
    image: pfidr/rclone:1.56.2
    container_name: gdrive-delete-torrents
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/gdrive:/config
      - ./rclone_mod_entrypoint.sh:/entrypoint.sh
    labels:
      - "group=maintenance"
    environment:
      SYNC_SRC: ${GDRIVE_SERVICE}:/torrent/complete/
      SYNC_OPTS: '--log-level ${LOG_LEVEL} --min-age=3d && rclone rmdirs ${GDRIVE_SERVICE}:/torrent/complete/ --config /config/rclone.conf --leave-root'
      RCLONE_DIR_CHECK_SKIP: 'true'
      RCLONE_CMD: delete
      TZ: ${DOCKER_TZ}
      CRON: ${MOVE_CRON}
      UID: ${PUID}
      GID: ${PGID}
      FORCE_SYNC: '1'

  gdrive-delete-nzb:
    image: pfidr/rclone:1.56.2
    container_name: gdrive-delete-nzb
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/gdrive:/config
      - ./rclone_mod_entrypoint.sh:/entrypoint.sh
    labels:
      - "group=maintenance"
    environment:
      SYNC_SRC: ${GDRIVE_SERVICE}:/nzb/complete/
      SYNC_OPTS: '--log-level ${LOG_LEVEL} --min-age=3d && rclone rmdirs ${GDRIVE_SERVICE}:/nzb/complete/ --config /config/rclone.conf --leave-root'
      RCLONE_DIR_CHECK_SKIP: 'true'
      RCLONE_CMD: delete
      TZ: ${DOCKER_TZ}
      CRON: ${MOVE_CRON}
      UID: ${PUID}
      GID: ${PGID}
      FORCE_SYNC: '1'