version: '3.7'

services:
  autoremove-torrents:
    image: dantebarba/autoremove-torrents:1.7.1-b1
    container_name: autoremove-torrents
    restart: unless-stopped
    volumes:
      - ${STORAGE_LOCATION}/autoremove-torrents/config.yml:/app/config.yml
    environment:
      TZ: ${DOCKER_TZ}
      CRON: ${CRON}
      OPTS: ${OPTS}
    networks:
      - main


networks: 
  main:
    external: true
